substitutions:
  name: "laterna-template"

esphome:
  name: "${name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true
  
  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: esphome.laterna-template
    version: "1.0"

esp32:
  board: esp32dev
  framework:
    type: arduino

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:

dashboard_import:
  package_import_url: github://Planet-Laterna/Laterna-ESPHome-template/laterna-template.yamlv1.0.0

wifi:
  # Set up a wifi access point
  ap:
    password: "12345678"

captive_portal:

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO21
    num_leds: 60
    rgb_order: BRG
    name: "Laterna WS2812B Light"
